apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: default
spec:
  serviceName: "minecraft-service"
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: minecraft-server
          image: 625392048444.dkr.ecr.us-east-1.amazonaws.com/cs312-minecraft-server:v1.0.0 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 25565
              name: minecraft
          envFrom:
            - configMapRef:
                name: minecraft-config
          resources:
            requests:
              memory: "2.5Gi"
              cpu: "1000m"
            limits:
              memory: "3Gi"
              cpu: "1500m"
          startupProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 15
          livenessProbe:
            tcpSocket:
              port: 25565
            periodSeconds: 20
          volumeMounts:
            - name: minecraft-data
              mountPath: /data

        # FINALLY FIXED SIDECAR FOR MC-MONITOR EXPORTER
        - name: minecraft-metrics
          image: itzg/mc-monitor:latest
          args:
            - export-for-prometheus
            - -servers
            - "127.0.0.1:25565"
          ports:
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              memory: "48Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
  volumeClaimTemplates:
    - metadata:
        name: minecraft-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi